from datetime import datetime, time

from fastapi import APIRouter
from sqlalchemy import func

from app.core.config import settings
from app.database.database import SessionLocal
from app.database.models import PredictionHistory

router = APIRouter(
    prefix="/dashboard",
    tags=["Dashboard"]
)


def get_market_status():
    now = datetime.now()

    if now.weekday() >= 5:
        return "CLOSED"

    current_time = now.time()

    pre_open_start = time(9, 0)
    market_open = time(9, 15)
    market_close = time(15, 30)

    if pre_open_start <= current_time < market_open:
        return "PRE-OPEN"

    elif market_open <= current_time <= market_close:
        return "OPEN"

    return "CLOSED"


@router.get("")
def dashboard():

    db = SessionLocal()

    try:

        total = db.query(PredictionHistory).count()

        buy = (
            db.query(PredictionHistory)
            .filter(PredictionHistory.signal == "BUY")
            .count()
        )

        sell = (
            db.query(PredictionHistory)
            .filter(PredictionHistory.signal == "SELL")
            .count()
        )

        hold = (
            db.query(PredictionHistory)
            .filter(PredictionHistory.signal == "HOLD")
            .count()
        )

        avg_confidence = (
            db.query(func.avg(PredictionHistory.confidence))
            .scalar()
            or 0
        )

        latest = (
            db.query(PredictionHistory)
            .order_by(PredictionHistory.created_at.desc())
            .first()
        )

        recent = (
            db.query(PredictionHistory)
            .order_by(PredictionHistory.created_at.desc())
            .limit(10)
            .all()
        )

        today = datetime.now().date()

        today_predictions = (
            db.query(PredictionHistory)
            .filter(func.date(PredictionHistory.created_at) == today)
            .count()
        )

        active_symbols = (
            db.query(
                func.count(
                    func.distinct(PredictionHistory.symbol)
                )
            )
            .scalar()
            or 0
        )

        win_rate = round(
            (buy / total * 100),
            2
        ) if total else 0

        dashboard = {

            "summary": {

                "total_predictions": total,
                "buy_signals": buy,
                "sell_signals": sell,
                "hold_signals": hold,
                "average_confidence": round(
                    avg_confidence,
                    2
                ),

            },

            "latest_prediction": None,

            "recent_predictions": [],

            "system": {

                "backend_status": "ONLINE",
                "database": "CONNECTED",
                "model": "LOADED",
                "market_status": get_market_status(),
                "upstox": "CONNECTED",

                "last_updated": (
                    latest.created_at.strftime("%d-%m-%Y %H:%M:%S")
                    if latest
                    else None
                ),

            },

            "statistics": {

                "today_predictions": today_predictions,
                "win_rate": win_rate,
                "active_symbols": active_symbols,
                "api_version": settings.APP_VERSION,

            },

        }

        if latest:

            risk = abs(
                latest.entry_price - latest.stop_loss
            )

            reward = abs(
                latest.target_price - latest.entry_price
            )

            risk_reward = round(
                reward / risk,
                2
            ) if risk != 0 else 0

            recommendation = "HOLD"

            if latest.signal == "BUY":
                recommendation = (
                    "Strong BUY"
                    if latest.confidence >= 75
                    else "BUY"
                )

            elif latest.signal == "SELL":
                recommendation = (
                    "Strong SELL"
                    if latest.confidence >= 75
                    else "SELL"
                )

            reason = (
                "High confidence prediction generated by AI model."
                if latest.confidence >= 75
                else "Prediction generated with moderate confidence."
            )

            dashboard["latest_prediction"] = {

                "symbol": latest.symbol,

                "signal": latest.signal,

                "confidence": latest.confidence,

                "entry_price": latest.entry_price,

                "target_price": latest.target_price,

                "stop_loss": latest.stop_loss,

                "risk_reward": risk_reward,

                "expected_return": latest.expected_return,

                "recommendation": recommendation,

                "reason": reason,

                "created_at": latest.created_at,

            }

        dashboard["recent_predictions"] = [

            {

                "symbol": p.symbol,

                "signal": p.signal,

                "confidence": p.confidence,

                "created_at": p.created_at,

            }

            for p in recent

        ]

        return dashboard

    finally:

        db.close()